"use client";
import { useEffect, useState } from "react";
import type { AnalysisResult } from "@/types";

const defaults = { location: "Kochi", rainfall: 120, windSpeed: 75, temperature: 29, humidity: 88, type: "RESIDENTIAL", value: 5000000 };
const scenarios = { low: { ...defaults, rainfall: 8, windSpeed: 12, temperature: 27, humidity: 55 }, medium: { ...defaults, rainfall: 55, windSpeed: 38, temperature: 31, humidity: 72 }, high: defaults };

export function AnalysisWorkspace() {
  const [mode, setMode] = useState<"scenario" | "live">("scenario");
  const [values, setValues] = useState(defaults); const [result, setResult] = useState<AnalysisResult | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [liveStatus, setLiveStatus] = useState("");
  useEffect(() => { if (new URLSearchParams(window.location.search).get("mode") === "live") setMode("live"); }, []);
  const update = (key: string, value: string) => setValues((v) => ({ ...v, [key]: key === "location" || key === "type" ? value : Number(value) }));
  const loadScenario = (name: keyof typeof scenarios) => { setValues(scenarios[name]); setResult(null); setError(""); };
  async function analyze() { setLoading(true); setError(""); try { const payload = { location: values.location, weather: { rainfall: Number(values.rainfall), windSpeed: Number(values.windSpeed), temperature: Number(values.temperature), humidity: Number(values.humidity) }, property: { type: values.type, value: Number(values.value) } }; const response = await fetch("/api/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || data.error || data.issues?.map((x: any) => x.message).join(" ") || "Please check your inputs."); if (!data.result) throw new Error("The analysis response did not contain a result."); setResult(data.result); } catch (e) { setError(e instanceof Error ? e.message : "The analysis could not be completed."); } finally { setLoading(false); } }
  function useLocation() { setLiveStatus("Requesting browser location…"); if (!navigator.geolocation) { setLiveStatus("Location access is unavailable. Enter a location manually."); return; } navigator.geolocation.getCurrentPosition(async (position) => { const { latitude, longitude } = position.coords; setLiveStatus(`Location found (${latitude.toFixed(2)}, ${longitude.toFixed(2)}). Live provider lookup requires WEATHER_API_KEY.`); }, () => setLiveStatus("Location access was unavailable. Enter a location manually.")); }
  return <section className="workspace">
    <div className="tabs"><button className={mode === "scenario" ? "tab active" : "tab"} onClick={() => setMode("scenario")}>Scenario Analysis</button><button className={mode === "live" ? "tab active" : "tab"} onClick={() => setMode("live")}>Live Area</button></div>
    {mode === "live" && <div className="live-card"><h2>Your area</h2><p>Use your browser location to prepare a live-weather analysis. The weather provider must be configured on the server.</p><button className="secondary-button" onClick={useLocation}>Use My Current Location</button><p className="muted">{liveStatus || "Live weather is not configured yet. Manual scenario mode is always available."}</p></div>}
    <div className="quick"><span>Quick scenarios</span><button onClick={() => loadScenario("low")}>Low Risk</button><button onClick={() => loadScenario("medium")}>Medium Risk</button><button onClick={() => loadScenario("high")}>High Risk</button><button onClick={() => { setValues(defaults); setResult(null); setError(""); }}>Reset</button></div>
    <div className="form-grid"><div className="panel"><h2>Weather conditions</h2><div className="fields"><Field label="Location" name="location" value={values.location} onChange={update} /><Field label="Rainfall (mm)" name="rainfall" type="number" value={values.rainfall} onChange={update} /><Field label="Wind speed (km/h)" name="windSpeed" type="number" value={values.windSpeed} onChange={update} /><Field label="Temperature (°C)" name="temperature" type="number" value={values.temperature} onChange={update} /><Field label="Humidity (%)" name="humidity" type="number" value={values.humidity} onChange={update} /></div></div><div className="panel"><h2>Property details</h2><div className="fields"><label>Property type<select value={values.type} onChange={(e) => update("type", e.target.value)}><option value="RESIDENTIAL">Residential</option><option value="COMMERCIAL">Commercial</option><option value="OTHER">Other</option></select></label><Field label="Property value (₹)" name="value" type="number" value={values.value} onChange={update} /></div><button className="primary-button" onClick={analyze} disabled={loading}>{loading ? "Analyzing weather conditions…" : mode === "live" ? "Analyze My Area" : "Analyze Damage Risk"}</button></div></div>
    {error && <div className="alert">{error}<button onClick={() => setMode("scenario")}>Switch to Manual Scenario</button></div>}
     {result && <Results result={result} />}
  </section>;
}
function Field({ label, name, value, onChange, type = "text" }: any) { return <label>{label}<input name={name} type={type} value={value} onChange={(e) => onChange(name, e.target.value)} min={type === "number" ? 0 : undefined} /></label>; }
function Results({ result }: { result: AnalysisResult }) { const flags = result.flags; return <div className="results"><div className="result-hero"><div><span className="eyebrow">Overall risk</span><strong>{result.risk.level}</strong></div><div><span className="eyebrow">Predicted damage</span><b>{result.damage.label || result.damage.type}</b></div><div><span className="eyebrow">Severity</span><b>{result.severity.severity}</b></div><div><span className="eyebrow">Estimated repair cost</span><b>₹{result.cost.min.toLocaleString("en-IN")} – ₹{result.cost.max.toLocaleString("en-IN")}</b></div></div><div className="result-grid"><div className="panel"><h2>Boolean conditions</h2>{[["Heavy Rain",flags.heavyRain],["High Wind",flags.highWind],["Extreme Temperature",flags.extremeTemperature],["High Humidity",flags.highHumidity]].map(([label, value]) => <p className="condition" key={String(label)}><span>{label}</span><strong className={value ? "true" : "false"}>{value ? "TRUE" : "FALSE"}</strong></p>)}</div><div className="panel"><h2>Logic trace</h2>{result.ruleTrace.map((rule) => <div className="trace" key={rule.id}><b>{rule.id} · {rule.expression}</b><span className={rule.result ? "true" : "false"}>{rule.result ? "TRUE" : "FALSE"}</span><small>{rule.explanation}</small></div>)}</div></div><div className="panel reasoning"><h2>Reasoning & recommendations</h2><p>{result.damage.explanation}</p><p>{result.severity.reason}</p><ul>{result.recommendations.map((r, i) => <li key={r.id || i}>{r.message}</li>)}</ul><p className="muted">{result.disclaimer}</p></div>{process.env.NODE_ENV === "development" && <details className="panel"><summary>Developer debug</summary><pre>{JSON.stringify({ rawInput: result.input, normalizedInput: result.input, flags: result.flags, risk: result.risk, damage: result.damage, severity: result.severity, cost: result.cost }, null, 2)}</pre></details>}</div>; }
